<h2><?php echo $this->translate('Therapy'); ?>: <?php echo $this->therapy->getName(); ?></h2>
<table>
    <colgroup>
        <col witdh="200">
        <col witdh="200">
        <col width="200">
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->translate('Price'); ?></th>
            <th><?php echo $this->translate('Since'); ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $prices = $this->therapy->getTherapyPrices(); ?>
        <?php if(!count($prices)): ?>
            <tr>
                <td colspan="2">
                    <?php echo $this->translate('Currently the system does not contain any therapy prices for current therapy'); ?>
                </td>
            </tr>
        <?php endif; ?>
        <?php foreach ($prices as $price): ?>
            <tr id="therapyPrice_<?php echo $price->getTherapyId(); ?>_<?php echo $price->getFromDate()->toString('ddMMyyyy'); ?>">
                <td>&euro;<?php echo $price->getPricePerHour(); ?></td>
                <td><?php echo $price->getFromDate()->toString('dd-MM-yyyy'); ?></td>
                <td>
                    <?php if (count($prices) > 1): ?>
                        <button id="delete"><?php echo $this->translate('Delete'); ?></button>
                        <script type="text/javascript">
                            $(function() {
                                $("tr#therapyPrice_<?php echo $price->getTherapyId(); ?>_<?php echo $price->getFromDate()->toString('ddMMyyyy'); ?> button#delete").button({icons: { primary: "ui-icon-trash" }});
                                $("tr#therapyPrice_<?php echo $price->getTherapyId(); ?>_<?php echo $price->getFromDate()->toString('ddMMyyyy'); ?> button#delete").click(function() {
                                    $("#dialog").html('Are you sure you want to delete <?php echo $price; ?> ? ');
                                    $("#dialog").dialog({
                                        title: 'Confirmation required:',
                                        modal: true, 
                                        resizable: false,
                                        buttons: [
                                            {
                                                text: 'Cancel',
                                                click: function() { 
                                                    $(this).dialog('close');
                                                }
                                            },
                                            {
                                                text: 'Confirm',
                                                click: function() {
                                                    $.ajax({
                                                        url: '<?php echo $this->url(array('action' => 'deleteprice', 'therapyId' => $price->getTherapyId(), 'fromDate' => $price->getFromDate()->toString('dd-MM-yyyy'), 'format' => 'json')); ?>',
                                                        success: function(data) {
                                                            $.ajax({
                                                                url: '<?php echo $this->url(array('action' => 'view', 'id' => $price->getTherapyId(), 'format' => 'html')); ?>',
                                                                success: function(data) {
                                                                    $('#dialog').dialog('close');
                                                                    $('#main-content').block();
                                                                    setTimeout(
                                                                        function() {
                                                                            $("#main-content").fadeOut();
                                                                            $("#main-content").html(data);
                                                                            $('#main-content').unblock();
                                                                            $("#main-content").fadeIn();
                                                                        },
                                                                        250
                                                                    );
                                                                }
                                                            });
                                                        }
                                                    });
                                                }
                                            }
                                        ]
                                    });
                                    $("#dialog").dialog({close: function(event, ui) { $(this).dialog('destroy'); $(this).html(''); } });
                                    $("#dialog").dialog("open");
                                });
                            });
                        </script>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="3">&nbsp;</th>
        </tr>
    </tfoot>
</table>
<button id="create"><?php echo $this->translate('Create'); ?></button>
<script type="text/javascript">
    $(function() {
        $("button#create").button({icons: { primary: "ui-icon-plusthick" }});

        $("button#create").click(function() {
            $.ajax({
                url: '<?php echo $this->url(array('controller' => 'therapy', 'action' => 'addprice', 'format' => 'html')); ?>',
                success: function(data) {
                    $("#dialog").html(data);
                    $("#dialog").dialog(
                        {
                            title: 'Add new therapy price',
                            modal: true, 
                            resizable: false,
                            autoOpen: true,
                            open: function(event, ui) { $("#dialog input[type=submit]").button(); },
                            close: function(event, ui) { $(this).dialog('destroy'); $(this).html(''); }
                        }
                    );
                }
            });
        });
    });
</script>
