<table>
    <colgroup>
        <col witdh="400">
        <col width="200">
    </colgroup>
    <thead>
    </thead>
    <tbody>
        <?php if(!count($this->appointments)): ?>
            <tr>
                <td colspan="2">
                    <?php echo $this->translate('Currently the system does not contain any appointments'); ?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if(count($this->appointments)): foreach ($this->appointments as $appointment): ?>
            <tr id="appointment_<?php echo $appointment->getId(); ?>">
                <td><?php echo $appointment; ?></td>
                <td>
                    <?php if ($appointment->getDate()->isLater(new Zend_Date())): ?>
                        <button id="update">Update</button>
                        <button id="delete">Delete</button>
                        <script type="text/javascript">
                            $(function() {
                                $("tr#appointment_<?php echo $appointment->getId(); ?> button#update").button({icons: { primary: "ui-icon-tag" }});
                                $("tr#appointment_<?php echo $appointment->getId(); ?> button#update").click(function() {
                                    $.ajax({
                                        url: '<?php echo $this->url(array('action' => 'update', 'id' => $appointment->getId(), 'format' => 'html')); ?>',
                                        success: function(data) {
                                            $("#dialog").html(data);
                                            $("#dialog").dialog({
                                                title: 'Update appointment',
                                                modal: true, 
                                                resizable: false,
                                                autoOpen: true,
                                                open: function(event, ui) { $("#dialog input[type=submit]").button(); },
                                                close: function(event, ui) { $(this).dialog('destroy'); $(this).html(''); }
                                            });
                                        }
                                    });
                                });
                                $("tr#appointment_<?php echo $appointment->getId(); ?> button#delete").button({icons: { primary: "ui-icon-trash" }});
                                $("tr#appointment_<?php echo $appointment->getId(); ?> button#delete").click(function() {
                                    $("#dialog").html('Are you sure you want to delete <?php echo $appointment; ?> ? ');
                                    $("#dialog").dialog({
                                        title: 'Confirmation required:',
                                        modal: true, 
                                        resizable: false,
                                        buttons: [
                                            {
                                                text: 'Cancel',
                                                click: function() { 
                                                    $(this).dialog('close');
                                                }
                                            },
                                            {
                                                text: 'Confirm',
                                                click: function() {
                                                    $.ajax({
                                                        url: '<?php echo $this->url(array('action' => 'delete', 'id' => $appointment->getId(), 'format' => 'html')); ?>',
                                                        success: function(data) {
                                                            $.ajax({
                                                                url: '<?php echo $this->url(array('action' => 'index', 'format' => 'html')); ?>',
                                                                success: function(data) {
                                                                    $('#dialog').dialog('close');
                                                                    $('#main-content').block();
                                                                    setTimeout(
                                                                        function() {
                                                                            $("#main-content").fadeOut();
                                                                            $("#main-content").html(data);
                                                                            $('#main-content').unblock();
                                                                            $("#main-content").fadeIn();
                                                                        },
                                                                        250
                                                                    );
                                                                }
                                                            });
                                                        }
                                                    });
                                                }
                                            }
                                        ]
                                    });
                                    $("#dialog").dialog({close: function(event, ui) { $(this).dialog('destroy'); $(this).html(''); } });
                                    $("#dialog").dialog("open");
                                });
                            });
                        </script>
                    <?php else: ?>
                        &nbsp;
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; endif; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2"><em><?php echo $this->translate('Only appointments in the future can be updated or deleted'); ?></em></td>
        </tr>
    </tfoot>
</table>
